const imagesData = [
    {
      img: 'https://www.la-viande.fr/sites/default/files/styles/slider_recettes/public/recettes/images/burger-de-hampe-de-boeuf-a-laustralienne.jpg',
      title: 'Mon burger',
      description: 'Burger fait maison, recette Auvergnate',
      author: 'aucun',
      cols: 1,
    },
    {
      img: 'https://assets.afcdn.com/recipe/20151003/20052_w1024h768c1cx480cy300.jpg',
      title: 'Pizza',
      description: 'Pizza fait maison',
      author: 'aucun',
      cols: 1,
    },
    {
      img: 'https://www.la-viande.fr/sites/default/files/styles/slider_recettes/public/recettes/images/burger-de-hampe-de-boeuf-a-laustralienne.jpg',
      title: 'Mon burger',
      description: 'Burger fait maison, recette Auvergnate',
      author: 'aucun',
      cols: 1,
    },
    {
      img: 'https://assets.afcdn.com/recipe/20151003/20052_w1024h768c1cx480cy300.jpg',
      title: 'Pizza',
      description: 'Pizza fait maison',
      author: 'aucun',
      cols: 1,
    },
    {
      img: 'https://www.la-viande.fr/sites/default/files/styles/slider_recettes/public/recettes/images/burger-de-hampe-de-boeuf-a-laustralienne.jpg',
      title: 'Mon burger',
      description: 'Burger fait maison, recette Auvergnate',
      author: 'aucun',
      cols: 1,
    },
    {
      img: 'https://assets.afcdn.com/recipe/20151003/20052_w1024h768c1cx480cy300.jpg',
      title: 'Pizza',
      description: 'Pizza fait maison',
      author: 'aucun',
      cols: 1,
    },
    {
      img: 'https://www.la-viande.fr/sites/default/files/styles/slider_recettes/public/recettes/images/burger-de-hampe-de-boeuf-a-laustralienne.jpg',
      title: 'Mon burger',
      description: 'Burger fait maison, recette Auvergnate',
      author: 'aucun',
      cols: 1,
    },
    {
      img: 'https://assets.afcdn.com/recipe/20151003/20052_w1024h768c1cx480cy300.jpg',
      title: 'Pizza',
      description: 'Pizza fait maison',
      author: 'aucun',
      cols: 1,
    },
    {
      img: 'https://www.la-viande.fr/sites/default/files/styles/slider_recettes/public/recettes/images/burger-de-hampe-de-boeuf-a-laustralienne.jpg',
      title: 'Mon burger',
      description: 'Burger fait maison, recette Auvergnate',
      author: 'aucun',
      cols: 1,
    },
    {
      img: 'https://assets.afcdn.com/recipe/20151003/20052_w1024h768c1cx480cy300.jpg',
      title: 'Pizza',
      description: 'Pizza fait maison',
      author: 'aucun',
      cols: 1,
    },
    {
      img: 'https://www.la-viande.fr/sites/default/files/styles/slider_recettes/public/recettes/images/burger-de-hampe-de-boeuf-a-laustralienne.jpg',
      title: 'Mon burger',
      description: 'Burger fait maison, recette Auvergnate',
      author: 'aucun',
      cols: 1,
    },
    {
      img: 'https://assets.afcdn.com/recipe/20151003/20052_w1024h768c1cx480cy300.jpg',
      title: 'Pizza',
      description: 'Pizza fait maison',
      author: 'aucun',
      cols: 1,
    },
  ];
  
  export default imagesData;